application:
  recover:
    no-recover-for:
      - java.lang.IllegalArgumentException
      - java.lang.IllegalStateException
  logging:
    enabled: true
    level: WARN
    print-args: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myNewDB
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    dialect:PostgresSQLDialect:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false