
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myNewDB_1
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      show-sql: true
      ddl-auto: create
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
        hibernate:
          format_sql: true