server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myNewDB_1
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      show-sql: true
      ddl-auto: create
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgresSQLDialect
        hibernate:
          format_sql=true:
logging:
  level:
    root: INFO